config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'rails/generate'

  get 'rails/controller'

  get 'rails/Sessions'

  get 'rails/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  # provide users resource
  resources :users

  # Session routes
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Create an editable variable 'remember_token' for use in 
  # the remember me digests for the user
  attr_accessor :remember_token
  
	# before_save callback to make sure email is lowercase
	before_save { self.email = self.email.downcase }

	# Make sure user has a name with acceptable length (MAX = 50)
	validates :name,  presence: true, length: { maximum: 50 }	

	# Valid email regex (regular expression) to check email format
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i

	# Make sure user has an email with acceptable length (MAX = 255)
	# Also ensure that there are no duplicate emails (for obvious reasons)
	validates :email, presence: true, length: { maximum: 255 },
									  format: { with: VALID_EMAIL_REGEX },
									  uniqueness: { case_sensitive: false }

  # Make sure user has a secure password
  has_secure_password

  # Make sure user's password has correct length
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, length: { minimum: 6 }

  # a class method to manually create a password digest for
  # the given string 'password'. We will use this mainly
  # in integrations tests with test users where we need to 
  # fill in the attributes for a new user
  def User.digest(password)
  	# The computational cost for generating the password digest
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

  	# Create the password digest using BCrypt and 'cost'
  	digest = BCrypt::Password.create(password, cost: cost)
  end

  # Returns a urlsafe base64 string
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Create a new remember_me digest for the user for use in a persistent session.
  def remember
    # Give the user a remember_me token string
    self.remember_token = User.new_token

    # Store the digest of the remember_token in the user model
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  # Forgets the user, clearing the permanent session
  def forget
    update_attribute(:remember_digest, nil)
    # We don't need the below line because if we update remember_digest to nil, then
    # you cannot use the old remember_token anyway, so it is unnecessary
    # self.remember_token = nil
  end

  # Authenticate the user based on the remember_token
  # will return true if the given token matches our hash
  # If the remember_digest is nil, then we just return false
  # This will solve the VERY subtle bug of having 2 different browsers open and logging out
  # of one but not the other
  def authenticated?(remember_token)
    if remember_digest.nil?
      return false
    end
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # include the SessionHelper module for help in loggin in user
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	# temp variable for user
  	user = User.find_by(email: params[:session][:email])

  	# Find user and then authenticate using provided password
  	if user && user.authenticate(params[:session][:password])
  		# log user in and redirect to 'show' page for the user
  		log_in user

      # We will remember the user on this computer if the 'remember_me' checkbox is checked
      if params[:session][:remember_me] == '1'
        remember user
      else
        forget user
      end

  		redirect_to user
  	else
  		# Otherwise, we just render 'new' and show an error message
  		# We use flash.now instead of just flash so that a render
  		# will clear the flash even though we don't send a new request
  		flash.now[:danger] = "Invalid email or password."

  		render 'new'
  	end
  end

  def destroy
    # call the log_out method in sessions_helper.rb ONLY if a user is logged in already
    # this avoids the subtle bug of having two concurrent browser windows open
    # and logging out in one of them but not the other
  	log_out if logged_in?

    # redirect to the home page
    redirect_to root_url # user URLS for 'redirect_to'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def show 
		@user = User.find(params[:id])
	end

	def new
		# create a new user (blank)
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save 
			# Handle success
			# Log user in automatically 
			log_in @user
			
			flash[:success] = "Welcome to the Sample App!"
			redirect_to user_url(@user)
		else
			render 'new'
		end
	end

	# Private methods
	private 

		# define user parameters
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# return full title for each page
	def full_title(page_title = '')
		# default title
		base_title = "Sample App"

		# If there is no title for the page, just use base_title
		if page_title.empty?
			base_title # return base_title
		else
			"#{page_title} | #{base_title}" # return concatenation of page+base titles
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Log in the user
	def log_in(user)
		# user 'session' to log in the given user
		session[:user_id] = user.id
	end

	# return the current logged in user
	def current_user
		# long way
		# if @current_user.nil?
			# @current_user = User.find_by(id: session[:user_id])
		# else
			# @current_user
		# end

		# cool way
		#@current_user ||= User.find_by(id: session[:user_id])

		# we need to support remember me tokens and permanent sessions
		# local variable to prevent accessing session multiple times uselessly
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			# temporary variable holding user
			user = User.find_by(id: user_id)

			# check if 'user' exists, and if so, authenticate its remember_token
			# we will use a helper function authenticated? for validation
			if user && user.authenticated?(cookies[:remember_token])
				# so if the user is valid and is authenticated, we will set 
				# @current_user to 'user' and log the user in
				log_in user
				@current_user = user
			end
		end
	end

	# returns if there is a user logged in, false otherwise
	# *** THIS CALLS 'current_user', NOT @current_user !!! ***
	def logged_in?
		!current_user.nil?
	end

	# logs the user out
	def log_out
		session.delete(:user_id)
		# The following line is equivalent to above
		# session[:user_id] = nil

		# forget the user
		forget(@current_user)

		# make sure we don't leave a @current_user lying around
		@current_user = nil
	end

	# Call the User class method 'remember' and set the cookies to create
	# a persistent session
	def remember(user)
		# call
		user.remember

		# set cookies to expire 20 years from now (standard convention)
		# the '.signed' ensures that 'user.id' is encrypted like session[:user_id] 
		# automatically does
		cookies.permanent.signed[:user_id] = user.id
		# the below code is the long version of the cookies.permanent method
		# cookies[:user_id] = { value:   user.id,
		# 					  expires: 20.years.from_now.utc }

		# we will also store the user's remember_token 
		# this is the equivalent of storing the raw password of the user for 'session'
		cookies.permanent[:remember_token] = user.remember_token
	end

	# opposite of 'remember(user)'
	# this method will forget a permanent session
	def forget(user)
		user.forget

		# clear the cookies
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://chrisjang.com">My Website</a>
	</small>

	<nav>
		<ul>
			<li><%= link_to 'About',   about_path %></li>
			<li><%= link_to 'Contact', contact_path %></li>
			<li><%= link_to 'News',    '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Sample App", root_path, id: "logo" %>

		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Help', help_path %></li>

				<!-- Show links based on logged_in? status -->
				<% if logged_in? %>
					<li><%= link_to 'Users', '#' %></li>
					<li class="dropdown">
						<!-- The hoverable link -->
						<a href='#' class='dropdown-toggle' data-toggle='dropdown'>
							Account <b class='caret'></b>
						</a>

						<!-- The list -->
						<ul class="dropdown-menu">
							<li><%= link_to 'Profile', current_user %></li>
							<li><%= link_to 'Settings', '#' %></li>
							<li class="divider"></li>
							<li><%= link_to	'Logout', logout_path, method: 'delete' %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to 'Log in', login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

		<!-- Shim -->
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<!-- Header shim -->
		<%= render 'layouts/header' %>
	
		<div class="container">
			<% flash.each do |msg_type, msg| %>
				<div class="alert alert-<%= msg_type %>">
					<%= msg %>
				</div>
			<% end %>

			<%= yield %>

			<!-- Footer Shim -->
			<%= render 'layouts/footer' %>

			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			<!-- Use pluralize() for correct grammar -->
			This form contains <%= pluralize(@user.errors.count, 'error') %>!
		</div>

		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>

<a href="/">Home</a>
<a href="/static_pages/help">Help</a>

<p>
	Chris Jang is a scrub that goes to the University of Illinois at Urbana-Champaign.
	He studies Computer Science and hopes to someday be a successful developer and possible launch his own company.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>

<p>Contact me at <a href="http://twitter.com/jangerino">my Twitter!</a></p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<a href="/">Back to Home</a>
<a href="/static_pages/about">About</a>
<p>If you need help shoot me a line: <a href="chrisjang.com" target="_blank">My website.</a></p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<% provide(:title, "Home") %>

	<h1>Welcome to the Sample App!</h1>

	<h2>This is the home page for the Sample App.</h2>

	<%= link_to 'Sign up', signup_path, class: 'btn btn-lg btn-primary' %>	
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<h1>Sign Up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: "poop form-control" %>

			<%= f.label :email %>
			<%= f.email_field :email, class: "form-control" %>

			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>

			<%= f.label :password_confirmation, "Confirm password" %>
			<%= f.password_field :password_confirmation, class: "form-control" %>

			<%= f.submit "Create my account", class: "btn btn-primary" %>

		<% end %>
	</div>	
</div>

app/views/users/show.html.erb
<!-- Provide title -->
<% provide(:title, @user.name) %>

<h1>
	<%= @user.name %>
</h1>

<%= @user.email %>